cms/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.list_of_posts, name='list_of_posts'),
	url(r'^(?P<slug>[-\w]+)/$', views.post_detail, name='post_detail'),
	url(r'^category/(?P<category_slug>[-\w]+)/$', views.list_of_posts_by_category, name='list_of_posts_by_category'),
	url(r'^(?P<slug>[-\w]+)/comment/$', views.add_comment, name='add_comment'),
	# backend
	url(r'^backend/post/new/$', views.new_post, name='new_post'),
	url(r'^backend/post/$', views.list_of_posts_backend, name='list_of_posts_backend'),
	url(r'^backend/(?P<slug>[-\w]+)/edit/$', views.edit_post, name='edit_post'),
	url(r'^backend/(?P<slug>[-\w]+)/delete/$', views.delete_post, name='delete_post'),
]

cms/cms/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog'))
]

cms/blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# category
class Category(models.Model):
	name = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique=True)
	class Meta:
		ordering = ['name']
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def get_absolute_url(self):
		return reverse('blog:list_of_posts_by_category', args=[self.slug])

	def __str__(self):
		return self.name

# post
class Post(models.Model):
	STATUS_CHOICES = (
			('draft','Draft'),
			('published','Published'),
		)
	title = models.CharField(max_length=250)
	category = models.ForeignKey(Category)
	slug = models.SlugField(max_length=250, unique=True)
	content = models.TextField()
	seo_title = models.CharField(max_length=250)	
	seo_descripttion = models.CharField(max_length=160)
	author = models.ForeignKey(User, related_name='blog_posts')
	published = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=9, choices=STATUS_CHOICES, default='draft')

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Post, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('blog:post_detail', args=[self.slug])

	def __str__(self):
		return self.title


class Comment(models.Model):
	post = models.ForeignKey(Post, related_name='comments')
	user = models.CharField(max_length=250)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	approved = models.BooleanField(default=False)

	def approved(self):
		self.approved = True
		self.save()

	def get_absolute_url(self):
		return reverse('blog:add_comment', args=[self.slug])

	def __str__(self):
		return self.user

cms/blog/forms.py
from django import forms
from .models import Comment, Post


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment # Hookup the model
		fields = ('user', 'email', 'body')


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'content', 'category', 'seo_title', 'seo_descripttion','status')

cms/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.contrib import messages
from .models import Post, Category
from .forms import CommentForm, PostForm


def list_of_posts_by_category(request, category_slug):
	categories = Category.objects.all()
	posts = Post.objects.filter(status='published')
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		posts = posts.filter(category=category)
	template = 'blog/category/list_of_posts_by_category.html'
	context = {'categories': categories, 'posts':posts, 'category':category}
	return render(request, template, context)


def list_of_posts(request):	
	posts = Post.objects.filter(status='published')
	paginator = Paginator(posts, 2)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.paginator(paginator.num_pages)
	template = 'blog/post/list_of_posts.html'
	context = {'posts':posts, 'page': page}
	return render(request, template, context)


def post_detail(request, slug):
	post = get_object_or_404(Post, slug=slug)
	context = {'post':post}
	if post.status == 'published':
		template = 'blog/post/post_detail.html'
		return render(request, template, context)
	else:
		template = 'blog/post/post_preview.html'
		return render(request, template, context)


def add_comment(request, slug):
	post = get_object_or_404(Post, slug=slug)
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.post = post
			comment.save()		
			return redirect('blog:post_detail', slug=post.slug)
	else:
		form = CommentForm()
	template = 'blog/post/add_comment.html'
	context = {'form':form}
	return render(request, template, context)

#############
# Backend
#############
def new_post(request):
	if request.method == 'POST':
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.save()
			return redirect('blog:post_detail', slug=post.slug)
	else:
		form = PostForm()
	template = 'blog/backend/new_post.html'
	context = {'form':form}
	return render(request, template, context)


def list_of_posts_backend(request):	
	posts = Post.objects.all()
	paginator = Paginator(posts, 2)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.paginator(paginator.num_pages)
	template = 'blog/backend/list_of_posts_backend.html'
	context = {'posts':posts, 'page': page}
	return render(request, template, context)

def edit_post(request, slug):
	post = get_object_or_404(Post, slug=slug)
	if request.method == 'POST':
		form = PostForm(request.POST, instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.save()
			return redirect('blog:list_of_posts_backend', )
	else:
		form = PostForm(instance=post)
	template = 'blog/backend/new_post.html'
	context = {'form':form}
	return render(request, template, context)


def delete_post(request, slug):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	post = get_object_or_404(Post, slug=slug)
	post.delete()
	messages.success(request, "Successfully Deleted!")
	return redirect('blog:list_of_posts_backend')

cms/blog/templates/blog/backend/list_of_posts_backend.html
{% extends "blog/base.html" %}
{% block description %}All blog posts{% endblock %}
{% block title %}Backend Posts{% endblock %}
{% block content %}
<div class="table-responsive">
	<table class="table table-hovered">
		<tr>
			<th>Title</th>
			<th>Slug</th>
			<th>Author</th>
			<th>Published</th>
			<th>Status</th>
			<th>Edit Post</th>
			<th>Delete Post</th>
		</tr>
		{% for post in posts %}
			{% if post.status == 'draft' %}
				<tr class="warning">
			{% else %}
				<tr>		
			{% endif %}
					<td>{{post.title}}</td>
					<td>{{post.slug}}</td>
					<td>{{post.author}}</td>
					<td>{{post.published}}</td>
					<td>{{post.status}}</td>
					<td><a href="{% url 'blog:edit_post' slug=post.slug %}" class="btn btn-info"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit</a></td>
					<td><a href="{% url 'blog:delete_post' slug=post.slug %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete</a></td>
				</tr>
		{% endfor %}
	</table>
	{% include 'blog/paginator.html' with page=posts %}
</div>
<!-- /.table-responsive -->
{% endblock content %}

cms/blog/templates/blog/backend/new_post.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>New Post</h1>
    <form action="" method="POST" class="post-form">
    	{% csrf_token %}
    	{{form|crispy}}
    	<button class="btn btn-success">Submit</button>
    </form>
{% endblock content %}

cms/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="author" content="{% block author %}{% endblock %}">
    <link rel="icon" href="">
	<title>{% block title %}{%endblock%}</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'css/ie10-viewport-bug-workaround.css' %}" type="text/css">
	<script type="text/javascript" src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<div class="container">
		{% include 'blog/frontend/navbar.html' %}
		{% include 'blog/messages.html' %}
		{% block content %}
		{% endblock %}		
	</div>
	<!-- /.container -->

	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

</body>
</html>

cms/blog/templates/blog/category/list_of_posts_by_category.html
{% extends "blog/base.html" %}
{% block description %}{{category.name}}{% endblock %}
{% block title %}{{category.name}}{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-8">
		<div class="page-header">
			<h1>Our Latest Posts in {{category.name}}</h1>
		</div>
		<!-- /.page-header -->
	{% for post in posts %}
		<h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
		<p>Written by {{post.author}} on {{post.published}}</p>		
		{{post.content|truncatewords:40|linebreaks}}
		<hr>
	{% endfor %}
	</div>
	<!-- /.col-md-8 -->
	<div class="col-md-4">
		<div class="page-header">
			<h2>Sidebar</h2>
		</div>
	</div>
	<!-- /.col-md-4 -->
{% endblock content %}
</div>
<!-- /.row -->

cms/blog/templates/blog/frontend/navbar.html
{% block content %}
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Bootstrap theme</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Post <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'blog:new_post' %}">New Post</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li class="dropdown-header">Nav header</li>
              <li><a href="#">Separated link</a></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
{% endblock content %}

cms/blog/templates/blog/messages.html
{% if messages %}
 {% for message in messages %}
	{% if message.tags %}		 	    
	 	<div class="alert alert-{{message.tags}}">{{message}}</div>
 	{% endif %} 	
 {% endfor %}
{% endif %}

cms/blog/templates/blog/paginator.html
<nav aria-label="Page navigation">
	{% if page.has_other_pages %}
	    <ul class="pagination">
	    	{% if page.has_previous %}
	    	   <li><a href="?page={{page.previous_page_number}}" aria-label="Previous">&laquo;</a></li>
	    	 {% else %} 
	    		<li class="disabled"><span>&laquo;</span></li>
	    	{% endif %}
	    	{% for pages in page.paginator.page_range %}
	    		{% if page.number == pages %}
	    			<li class="active"><span>{{pages}}<span class="sr-only">(current)</span></span></li>
	    		{% else %}	    		
	    			<li><a href="?page={{pages}}">{{pages}}</a></li>
	    		{% endif %}
	    	{% endfor %}
	    	{% if page.has_next %}	    	    
    			<li><a href="?page={{page.next_page_number}}">&raquo;</a></li>
    		{% else %}
				<li class="disabled"><span>&raquo;</span></li>
	    	{% endif %}
	    </ul>
	{% endif %}
</nav>

cms/blog/templates/blog/post/add_comment.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}New Comment{% endblock title %}
{% block content %}
<div class="row">
	<div class="col-md-8">
		<div class="page-header">
    		<h2>Post a Comment</h2>			
		</div>
		<!-- /.page-header -->
    <form action="" method="POST">
    	{% csrf_token %}
    	{{form|crispy}}
    	<button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>
	<!-- /.col-md-8 -->
	<div class="col-md-4">
		<div class="page-header">
			<h2>Sidebar</h2>
		</div>
		<!-- /.page-header -->
	</div>
	<!-- /.col-md-4 -->
</div>
<!-- /.row -->    
{% endblock content %}

cms/blog/templates/blog/post/list_of_posts.html
{% extends "blog/base.html" %}
{% block description %}All blog posts{% endblock %}
{% block title %}List of Posts{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-8">
		<div class="page-header">
			<h1>Our Latest Posts</h1>
		</div>
		<!-- /.page-header -->
		{% for post in posts %}
		<h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
		<small>Written by {{post.author}} on {{post.published}} in <a href="{{post.category.get_absolute_url}}">{{post.category}}</a></small>			
		<br>
		{{post.content|truncatewords:40|linebreaks}}
		<hr>	
		{% endfor %}	
		{% include 'blog/paginator.html' with page=posts %}
	</div>
	<!-- /.col-md-8 -->
	<div class="col-md-4">
		<div class="page-header">
			<h2>Sidebar</h2>
		</div>
	</div>
	<!-- /.col-md-4 -->
</div>
<!-- /.row -->
{% endblock content %}

cms/blog/templates/blog/post/post_detail.html
{% extends "blog/base.html" %}
{% block description %}{{post.seo_description}}{% endblock %}
{% block title %}{{post.seo_title}}{% endblock %}
{% block content %}	
<div class="row">
	<div class="col-md-8">
		<div class="page-header">
			<h2>{{post.title}}</h2>
		</div>
		<!-- /.page-header -->		
		<p>Written by {{post.author}} on {{post.published}} in <a href="{{post.category.get_absolute_url}}">{{post.category}}</a></p>		
		{{post.content|linebreaks}}	
		<hr>
		<h4>Comments <small>Total Number of Comments {{post.comments.count}}</small></h4>		
		<p class="text-center">
			<a href="{% url 'blog:add_comment' slug=post.slug %}" class="btn btn-default">Leave a Comment</a>			
		</p>
		{% for comment in post.comments.all %}
			<div class="panel panel-default">
				<div class="panel-heading">
					{{comment.user}} <i>commented on {{comment.created}}</i>
				</div>
				<!-- /.panel-heading -->				
				<div class="panel-body">
					<p>{{comment.body}}</p>						
				</div>
				<!-- /.panel-body -->
			</div>
			<!-- /.panel panel-default -->			
			{% empty %}
			<p>There is no comment.</p>
		{% endfor %}
			</div>
	<!-- /.col-md-8 -->
	<div class="col-md-4">
		<div class="page-header">
			<h2>Sidebar</h2>
		</div>
	</div>
	<!-- /.col-md-4 -->
{% endblock content %}
</div>
<!-- /.row -->

cms/blog/templates/blog/post/post_preview.html
{% extends "blog/base.html" %}
{% block description %}{{post.seo_description}}{% endblock %}
{% block title %}{{post.seo_title}}{% endblock %}
{% block content %}	
<div class="row">
	<div class="col-md-8">
		<div class="alert alert-danger" role="alert">Preview of the Post</div>
		<div class="page-header">
			<h2>{{post.title}}</h2>
		</div>
		<!-- /.page-header -->		
		<p>Written by {{post.author}} on {{post.published}} in <a href="{{post.category.get_absolute_url}}">{{post.category}}</a></p>		
		{{post.content|linebreaks}}	
		<hr>
		<h4>Comments <small>Total Number of Comments {{post.comments.count}}</small></h4>		
		<p class="text-center">
			<a href="{% url 'blog:add_comment' slug=post.slug %}" class="btn btn-default">Leave a Comment</a>			
		</p>
		{% for comment in post.comments.all %}
			<div class="panel panel-default">
				<div class="panel-heading">
					{{comment.user}} <i>commented on {{comment.created}}</i>
				</div>
				<!-- /.panel-heading -->				
				<div class="panel-body">
					<p>{{comment.body}}</p>						
				</div>
				<!-- /.panel-body -->
			</div>
			<!-- /.panel panel-default -->			
			{% empty %}
			<p>There is no comment.</p>
		{% endfor %}
			</div>
	<!-- /.col-md-8 -->
	<div class="col-md-4">
		<div class="page-header">
			<h2>Sidebar</h2>
		</div>
	</div>
	<!-- /.col-md-4 -->
{% endblock content %}
</div>
<!-- /.row -->